### ISSUE TITLE
OpenSourceTB literature/papers tab

### ISSUE THREAD

**Issue by jessicabaiget** [OpenSourceTB/OpenSourceTB_To_Do_List#1]
Hi @mattodd 
I have this idea in mind, I would like to add a new  tab in the OSTB wiki at the same level of TB home/OSTBS so far/ compounds/…  called TB papers or relevant papers, and  make some sections such as  Biology papers, medchem papers,TB today inside this tab, so I can make the literature updating from here.

Do you like the idea? Also I think I will need some help to make the tab, but I will be happy to edit it

Thanks

Jessica

**Comment by mattodd** [comment]
Hmm. Interesting. You mean as a place to collect papers and other lit things relevant to TB and OSTB in particular? I wonder if there is a better place to put that, such as Mendeley, or maybe a Google+ community? I actually don't know what is the best place for something like this - it might be the wiki, and you might be right. Would you want something like the "links" page for OSM?

http://openwetware.org/wiki/OpenSourceMalaria:Links

or something different?

**Comment by mattodd** [comment]
Let me know if this is what you need

http://openwetware.org/wiki/OpenSourceTB:Links

or whether you're talking about something more interactive, like a discussion forum (we do have https://plus.google.com/u/0/communities/101893553189762547680)

Either way we should either close this Issue as resolved, or work out what else is needed here.

**Comment by jessicabaiget** [comment]
Hi @mattodd 
I will use the Link tab for the literature update, thank you. I think we can close this issue and consider it resolved.

Cheers

**Comment by mattodd** [comment]
OK, done!
